Pre-Release_to_master:
  only:
    - master
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
	- git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin --all
    - git merge refs/remotes/origin/Pre-Release
    - git remote -v
    - git push -u origin master
    
Gearz_to_Pre-Release:
  only:
    - Gearz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
	- git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Gearz
    - git remote -v
    - git push -u origin Pre-Release

Killerrabbit_to_Pre-Release:
  only:
    - Killerrabbit
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Killerrabbit
    - git remote -v
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git push -u origin Pre-Release

Divexz_to_Pre-Release:
  only:
    - Divexz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Divexz
    - git remote -v
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git push -u origin Pre-Release

Brostrom_to_Pre-Release:
  only:
    - Brostrom
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Brostrom
    - git remote -v
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git push -u origin Pre-Release

Aleksandar_to_Pre-Release:
  only:
    - Aleksandar
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Aleksandar
    - git remote -v
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git push -u origin Pre-Release
    
Niko92_to_Pre-Release:
  only:
    - Niko92
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Niko92
    - git remote -v
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git push -u origin Pre-Release

Imperator_to_Pre-Release:
  only:
    - Imperator
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Imperator
    - git remote -v
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git push -u origin Pre-Release
    
patch-4_to_Pre-Release:
  only:
    - patch-4
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/patch-4
    - git remote -v
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git push -u origin Pre-Release
    
MSG_to_Pre-Release:
  only:
    - MSG
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git pull origin --all
    - git checkout Pre-Release
    - git merge refs/remotes/origin/MSG
    - git remote -v
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git push -u origin Pre-Release
