stages:
  - Styling
  - Standards

Styling:
  stage: test
  image: python:3.6
  before_script:
    - apt-get update -q -y
    - apt-get install -y python3-dev python3-setuptools
  script:
    - python3 tools/check_basic_style.py
    - python3 tools/check_basic_style_2.py

Coding_Standards:
  stage: Standards
  image: python:3.6
  script:
    - python3 tools/coding_standards.py
    - allow_failure: true
    