Gearz_to_Pre-Release:
  only:
    - Gearz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Gearz
    - git remote set-url origin git@gitlab.com:truemikesmith/Modern_Day_4_HOI.git
    - git push origin Pre-Release

Killerrabbit_to_Pre-Release:
  only:
    - Killerrabbit
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Killerrabbit

Divexz_to_Pre-Release:
  only:
    - Divexz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Divexz

Brostrom_to_Pre-Release:
  only:
    - Brostrom
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Brostrom

Aleksandar_to_Pre-Release:
  only:
    - Aleksandar
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Aleksandar
    
Niko92_to_Pre-Release:
  only:
    - Niko92
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Niko92

Imperator_to_Pre-Release:
  only:
    - Imperator
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git checkout Pre-Release
    - git merge refs/remotes/origin/Imperator
    
patch-4_to_Pre-Release:
  only:
    - patch-4
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git checkout Pre-Release
    - git merge refs/remotes/origin/patch-4
    
  
