stages:
  - StandardsTest
  - StylingTest
  - FixStyling
  
CodingStandards:
  stage: StandardsTest
  image: python:3.6
  only:
    - merge_requests
  script:
    - export PR_ID=$(curl -s -L "http://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests?private_token=${$Bot_Token}&state=opened" | jq -r ".[]|select(.sha == \"$CI_COMMIT_SHA\")|.iid")
    - python3 tools/coding_standards.py $CI_PROJECT_ID $PR_ID $Bot_Token

Styling:
  stage: StylingTest
  image: python:3.6
  only:
    - merge_requests
  script:
    - python3 tools/check_basic_style_2.py

FixingStyling:
  stage: FixStyling
  image: python:3.6
  script:
    - python3 tools/fix_styling.py
  after_script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:$Bot_Token@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git add -A
    - git commit -m 'Fixed Styling for you'
    - git push -u origin HEAD:$CI_COMMIT_REF_NAME
    - python3 tools/check_basic_style.py
    - python3 tools/check_basic_style_2.py
    
  when: on_failure