test:
  script:
    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    - apt-get install -y python3.5
    - python check_leaderid.py

Gearz_to_master:
  only:
    - Gearz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Gearz
    - git remote -v
    - git push -u origin master

Killerrabbit_to_master:
  only:
    - Killerrabbit
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Killerrabbit
    - git remote -v
    - git push -u origin master

Divexz_to_master:
  only:
    - Divexz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Divexz
    - git remote -v
    - git push -u origin master

Brostrom_to_master:
  only:
    - Brostrom
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Brostrom
    - git remote -v
    - git push -u origin master

Aleksandar_to_master:
  only:
    - Aleksandar
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Aleksandar
    - git remote -v
    - git push -u origin master
    
Niko92_to_master:
  only:
    - Niko92-New-Branch
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Niko92-New-Branch
    - git remote -v
    - git push -u origin master

Imperator_to_master:
  only:
    - Imperator
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Imperator
    - git remote -v

    - git push -u origin master
    
patch-4_to_master:
  only:
    - patch-4
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/patch-4
    - git remote -v
    - git push -u origin master
    
MSG_to_master:
  only:
    - MSG
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/MSG
    - git remote -v
    - git push -u origin master

PrimeMinisterSinister_to_master:
  only:
    - PrimeMinisterSinister
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/PrimeMinisterSinister
    - git remote -v
    - git push -u origin master

popkillerlight_to_master:
  only:
    - popkillerlight
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/popkillerlight
    - git remote -v
    - git push -u origin master
    
Tekoa_to_master:
  only:
    - Tekoa
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Tekoa
    - git remote -v
    - git push -u origin master

Beefbomber_to_master:
  only:
    - Beefbomber
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Beefbomber
    - git remote -v
    - git push -u origin master
    
RegularRabbit_to_master:
  only:
    - RegularRabbit
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/RegularRabbit
    - git remote -v
    - git push -u origin master

divexz_to_master:
  only:
    - divexz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/divexz
    - git remote -v
    - git push -u origin master

HansNery_to_master:
  only:
    - HansNery
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/HansNery
    - git remote -v
    - git push -u origin master
    
boots_to_master:
  only:
    - boots
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/boots
    - git remote -v
    - git push -u origin master
    
HoChiMinh_to_master:
  only:
    - HoChiMinh
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/HoChiMinh
    - git remote -v
    - git push -u origin master
    
Blueghost_to_master:
  only:
    - Blueghost
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Blueghost
    - git remote -v
    - git push -u origin master
 
Hassan_Arfa_to_master:
  only:
    - Hassan_Arfa
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Hassan_Arfa
    - git remote -v
    - git push -u origin master  
    
OttomanBear_to_master:
  only:
    - OttomanBear
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/OttomanBear
    - git remote -v
    - git push -u origin master

Aco_Tsar_to_master:
  only:
    - Aco_Tsar
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Aco_Tsar
    - git remote -v
    - git push -u origin master
    
Generalis_to_master:
  only:
    - Generalis
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Generalis
    - git remote -v
    - git push -u origin master
    
Walcanaruss_to_master:
  only:
    - Walcanarus
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Walcanarus
    - git remote -v
    - git push -u origin master
    
Jogarzs2ndBranch_to_master:
  only:
    - Jogarzs2ndBranch
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Jogarzs2ndBranch
    - git remote -v
    - git push -u origin master
    
ahmeteris_to_master:
  only:
    - ahmeteris
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/ahmeteris
    - git remote -v
    - git push -u origin master
    
GaiusMarius_to_master:
  only:
    - GaiusMarius-LOC
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/GaiusMarius-LOC
    - git remote -v
    - git push -u origin master   
    
StrategyGamer_to_master:
  only:
    - StrategyGamer
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/StrategyGamer
    - git remote -v
    - git push -u origin master
    
SpaceOut_to_master:
  only:
    - SpaceOut
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/SpaceOut
    - git remote -v
    - git push -u origin master
    