# cwtools-action v1.0, 2019-12-02
# Please occasionally check below for updates to this template
# https://github.com/cwtools/cwtools-action
# Example GitLab CI workflow file for a Stellaris project
# Will trigger when a merge request to master is created
# Rename to .gitlab-ci.yml and put in root of your repository

image: mcr.microsoft.com/dotnet/core/sdk:3.0

variables:
 DOCKER_DRIVER: overlay2
 GIT_STRATEGY: fetch # Please see https://github.com/cwtools/cwtools-action/issues/3 for details as to why this is needed
 INPUT_GAME: "hoi4" # Change to the game used in your project
 # Variables below are optional and set to their default values - uncomment and change them if you wish so
 #INPUT_MODPATH: ''
 #INPUT_CACHE: ''
 #INPUT_LOCLANGUAGES: 'english'
 #INPUT_RULES: ''
 #INPUT_RULESREF: 'master'
 #INPUT_VANILLAMODE: '0'
 #For CW226: Localisation key commands aren't supported, issue report here: https://github.com/cwtools/cwtools-hoi4-config/issues/65
 #for CW251: AND is unneededa warnings Bird Need to fix
 INPUT_SUPPRESSEDOFFENCECATEGORIES: '{"failure":["CW226"], "warning":["CW251"], "notice":[]}'
 #INPUT_SUPPRESSEDFILES: '[]'
 #INPUT_CWTOOLSCLIVERSION: ''

stages:
 - codingstandards
 - styling
 - CWTools_CI

Styling:
 stage: styling
 image: python:3.11
 only: [merge_requests]
 script:
  - pip install requests
  - python3 tools/coding_standards.py $Bot_Token

CodingStandards:
  stage: codingstandards
  image: python:3.6
  only:
    - merge_requests
  script:
    - pip install requests
    - python3 tools/check_basic_style_2.py $Bot_Token

CWTools_CI:
 stage: CWTools_CI
 only: [merge_requests]
 script:
  - echo "Pulling down the CWTools action validator"
  - wget -O - -q https://raw.githubusercontent.com/cwtools/cwtools-action/v1.0.0/lib/gitlab_setup.sh | sh -s

 # Optional, expose the CWTools errors in JSON
 artifacts:
  expose_as: 'CWTools Build Output'
  paths:
   - output.json
  when: always