stages:
  - StandardsTest
  - StylingTest
  - FixStyling
  
  
CodingStandards:
  stage: StandardsTest
  image: python:3.6
  only:
    - merge_requests
  script:
    - pip install requests
    - python3 tools/coding_standards.py $Bot_Token

Styling:
  stage: StylingTest
  image: python:3.6
  only:
    - merge_requests
  script:
    - pip install requests
    - python3 tools/check_basic_style_2.py $Bot_Token

FixingStyling:
  stage: FixStyling
  image: python:3.6
  only:
    - merge_requests
  script:
    - pip install requests
    - python3 tools/fix_styling.py
  after_script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:$Bot_Token@gitlab.com/Millennium_Dawn/Millennium_Dawn.git
    - git add -A
    - git commit -m 'Fixed Styling for you'
    - git push -u origin HEAD:$CI_COMMIT_REF_NAME
    - python3 tools/check_basic_style.py  $Bot_Token
    - python3 tools/check_basic_style_2.py $Bot_Token
    
  when: on_failure

  
  