deploy_to_master2:
  only:
    - Gearz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git checkout master
    - git merge refs/remotes/origin/Gearz