master_to_master:
  only:
    - master
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git merge refs/remotes/origin/master
    - git remote -v
    - git push -u origin master
    
Gearz_to_master:
  only:
    - Gearz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Gearz
    - git remote -v
    - git push -u origin master

Killerrabbit_to_master:
  only:
    - Killerrabbit
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Killerrabbit
    - git remote -v
    - git push -u origin master

Divexz_to_master:
  only:
    - Divexz
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Divexz
    - git remote -v
    - git push -u origin master

Brostrom_to_master:
  only:
    - Brostrom
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Brostrom
    - git remote -v
    - git push -u origin master

Aleksandar_to_master:
  only:
    - Aleksandar
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Aleksandar
    - git remote -v
    - git push -u origin master
    
Niko92_to_master:
  only:
    - Niko92-New-Branch
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Niko92-New-Branch
    - git remote -v
    - git push -u origin master

Imperator_to_master:
  only:
    - Imperator
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Imperator
    - git remote -v

    - git push -u origin master
    
patch-4_to_master:
  only:
    - patch-4
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/patch-4
    - git remote -v
    - git push -u origin master
    
MSG_to_master:
  only:
    - MSG
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/MSG
    - git remote -v
    - git push -u origin master

PrimeMinisterSinister_to_master:
  only:
    - PrimeMinisterSinister
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/PrimeMinisterSinister
    - git remote -v
    - git push -u origin master

popkillerlight_to_master:
  only:
    - popkillerlight
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/popkillerlight
    - git remote -v
    - git push -u origin master
    
Tekoa_to_master:
  only:
    - Tekoa
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Tekoa
    - git remote -v
    - git push -u origin master

Beefbomber_to_master:
  only:
    - Beefbomber
  script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git remote set-url origin https://MD4GitBot:fNU2AukwBpTSokMymzrx@gitlab.com/truemikesmith/Modern_Day_4_HOI.git
    - git pull origin master
    - git checkout master
    - git merge refs/remotes/origin/Beefbomber
    - git remote -v
    - git push -u origin master
    