stages:
  - StandardsTest
  - StylingTest
  - FixErrors
  - Deploy
  
CodingStandards:
  stage: StandardsTest
  image: python:3.6
  script:
    - python3 tools/coding_standards.py
  allow_failure: true

Styling:
  stage: StylingTest
  image: python:3.6
  script:
    - python3 tools/check_basic_style.py
    - python3 tools/check_basic_style_2.py

FixingStyling:
  stage: CleanUpTest
  image: python:3.6
  script:
    - python3 tools/fix_styling.py
  after_script:
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git git push origin HEAD:$CI_COMMIT_REF_NAME
    - python3 tools/check_basic_style.py
    - python3 tools/check_basic_style_2.py
    
  when: on_failure