stages:
  - StylingTest
  - StandardsTest

Styling:
  stage: StylingTest
  image: python:3.6
  script:
    - python3 tools/check_basic_style.py
    - python3 tools/check_basic_style_2.py

CodingStandards:
  stage: StandardsTest
  image: python:3.6
  script:
    - python3 tools/coding_standards.py
  allow_failure: true
    