stages:
  - StandardsTest
  - StylingTest
  - CleanUpTest
  
CodingStandards:
  stage: StandardsTest
  image: python:3.6
  script:
    - python3 tools/coding_standards.py
  allow_failure: true

Styling:
  stage: StylingTest
  image: python:3.6
  before_script:
    - apt-get update -q -y
    - apt-get install -y python3-dev python3-setuptools
  script:
    - python3 tools/check_basic_style.py
    - python3 tools/check_basic_style_2.py

cleanup:
  stage: CleanUpTest
  script:
    - python3 tools/fix_styling.py
    - git config --global user.email "x-mike-x_@live.com"
    - git config --global user.name "MD4GitBot"
    - git config --global push.default simple
    - git push

  when: on_failure


  

    