l_french:
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "Industries militaires"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "Industries civiles"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "Industries militaires disponibles"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "Industries civiles disponibles"
 PRODUCTION_PRODUCING_NO_FACTORIES:0 "§RAucune industrie assignée§! "
 PRODUCTION_EFFICIENCY_DESC:0 "§TEfficacité moyenne de la production industrielle. \n Augmentation de l’efficacité de la production de $VALEUR|H=2$% / unité produite répartie également entre les industries actives.§!"
 PRODUCTION_MATERIALS_OIL:0 "Pétrole"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "Métaux légers"
 PRODUCTION_MATERIALS_CHROMIUM:0 "NON UTILISÉ"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "Technologie des métaux"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED:0 "Nous n'avons §RAucune industrie militaire!§! "
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED:0 "Nous n'avons §RAucune industrie militaire!§! "
 PRODUCTION_CONSUMER_GOODS:0 "Coût des taxes"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§HCoût des taxes§! "
 PRODUCTION_CONSUMER_GOODS_DESC:0 "En raison des taxes et des diverses politiques, $POURCENTAGE|H0% de notre économie totale (industries civiles) ne sont pas disponibles. Cela nous laisse avec les industries $OPERATIONAL|H$ où $TRADE_USABLE|H$ peut être utilisé pour le commerce."
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "Industries civiles et militaires: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "Industrie civile nécessaire: $KEY|H$"
 PRODUCTION_WORKING_FACTORIES:0 "Il s'agit du nombre d'industries travaillant actuellement sur l'une de vos chaînes de production."
 PRODICTION_MIC_TRANSFERED:0 "$AMOUNT|Y$ de nos industries sont utilisées par $OVERLORD|Y$."
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT:0 "$MONTANT|Y$ des industries militaires sont reçues de nos sujets."
 PRODICTION_MIC_SENT_TO_OVERLORD:0 "$AMOUNT|R$de nos industries militaires sont données à notre suzerain et nous n'avons laissé que $LEFT|H$."
 PRODUCTION_OUTPUT_EXPLAIN:0 "Notre $FACTORIES|Y$£ factory_item Les industries militaires contribuent $SORTIE|Y$£ production_cost. \n $ITEM|Y$a un coût de $ITEM_COST|2Y$£ production_cost, ce qui signifie que nous pouvons produire $PERTIMEPERIOD$.\n"
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "Industries militaires utilisées"
 