title: "Millennium Dawn"
description: "Documentation for the Millennium Dawn mod for Hearts of Iron IV"
baseurl: "/Millennium-Dawn"
url: "https://millenniumdawnmod.github.io"

markdown: kramdown
highlighter: rouge
theme: minima

collections:
  guides:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - title: "Home"
    url: "/"
  - title: "Tutorials"
    url: "#tutorials"
  - title: "Team Resources"
    url: "#team-resources"
  - title: "Open-Source Resources"
    url: "#open-source-resources"
  - title: "Changelogs"
    url: "/changelogs"
  - title: "Dev Diaries"
    url: "/dev-diaries-list"
  - title: "List of Countries"
    url: "/countries-list"
  - title: "Code Stylization Guide"
    url: "/code-stylization-guide"

social:
  - name: "GitHub"
    url: "https://github.com/millenniumdawnmod/Millennium_Dawn"
  - name: "Steam Workshop"
    url: "https://steamcommunity.com/sharedfiles/filedetails/?id=1313149702"
